drop table if exists Ingredient_Ref;
drop table if exists Taco;
drop table if exists Taco_Order;
drop table if exists Ingredient;

create table Ingredient (
                            id varchar(4) not null,
                            name varchar(25) not null,
                            type varchar(10) not null,
                            primary key (id)
);

create table Taco_Order (
                            id bigint generated by default as identity primary key,
                            delivery_name varchar(50) not null,
                            delivery_street varchar(50) not null,
                            delivery_city varchar(50) not null,
                            delivery_state varchar(20) not null,
                            delivery_zip varchar(10) not null,
                            cc_number varchar(16) not null,
                            cc_expiration varchar(5) not null,
                            cc_cvv varchar(3) not null,
                            placed_at timestamp not null
);

create table Taco (
                      id bigint generated by default as identity primary key,
                      name varchar(50) not null,
                      created_at timestamp not null,
                      taco_order bigint not null,
                      taco_order_key bigint not null
);

create table Ingredient_Ref (
                                ingredient varchar(4) not null,
                                taco bigint not null,
                                taco_key bigint not null
);

alter table Taco
    add foreign key (taco_order) references Taco_Order(id);

alter table Ingredient_Ref
    add foreign key (ingredient) references Ingredient(id);

alter table Ingredient_Ref
    add foreign key (taco) references Taco(id);