spring.application.name=tacocloud

server.port=8085
spring.thymeleaf.cache=false

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://atlasuser:${MONGODB_PASSWORD}@cluster0.gh2dttt.mongodb.net/tacoclouddb